# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.16
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

  linter:
    docker:
    - image: circleci/node:10.16
    steps:
      - run:
          name: "Linter"
          command: npm run lint
  unit-test:
    docker:
      - image: circleci/node:10.16
    steps:
      - run:
        name: "Unit tests"
        command: npm run test
  e2e-test:
    docker:
    - image: circleci/node:10.16
    steps:
      - run:
        name: "End-to-end tests"
        command: npm run e2e

workflows:
  version: 2
  Main:
    jobs:
      - build
      - linter:
          requires:
            - build
      - unit-test:
          requires:
            - build
      - e2e-test:
          requires:
            - build

